name: My very first workflow

on: 
  push:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:

  OutputToLog:

    runs-on: ubuntu-latest
  
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List all files in the repository
        run: |
          echo "The repository ${{github.repository}} contains the following files"
          tree
          
        

  
